# =============================================================================
# compute_contrastive_excess_loss.py
#
# Pre-computes excess losses on BBH tasks using an expert model (base + LoRA)
# vs. an amateur model (base only). Outputs both:
#

# Sample command:
#   python compute_contrastive_excess_loss.py \
#       --task_name word_sorting \
#       --expert_model_name mistralai/Mistral-7B-Instruct-v0.3 \
#       --target_model_name mistralai/Mistral-7B-Instruct-v0.3
# =============================================================================

import os
import json
import argparse
from tqdm import tqdm

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from datasets import Dataset
from transformers import (
    set_seed,
    AutoModelForCausalLM,
    AutoTokenizer,
    DataCollatorForSeq2Seq,
)
from peft import PeftModel, prepare_model_for_kbit_training

# ---------------------------------------------------------------------------
# Synthetic data path
# ---------------------------------------------------------------------------
# Please set this to the full path of your synthetic data directory.
# Expected structure: {input_synthetic_data_path}/{task_name}_diverse_500_data.json
# The data should contain query+labels generated by the source/expert model.

input_synthetic_data_path = None  # e.g. "./synthetic_data/query_EXPERT_Mistral-7B-Instruct-v0.3_answer_EXPERT_Mistral-7B-Instruct-v0.3"

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Pre-compute excess losses on BBH tasks")
    parser.add_argument("--expert_model_name", type=str, default="mistralai/Mistral-7B-Instruct-v0.3",
                        help="Expert model (the one with LoRA adapter)")
    parser.add_argument("--target_model_name", type=str, default="mistralai/Mistral-7B-Instruct-v0.3",
                        help="Target model name (used for output directory naming)")
    parser.add_argument("--queries_from", type=str, default="EXPERT_Mistral-7B-Instruct-v0.3",
                        help="Tag indicating which model generated the query data (used for output directory naming)")
    parser.add_argument("--access_token", type=str, default=None)
    parser.add_argument("--task_name", type=str, required=True,
                        choices=[
                            "boolean_expressions", "causal_judgement", "date_understanding",
                            "disambiguation_qa", "dyck_languages", "formal_fallacies",
                            "geometric_shapes", "hyperbaton", "logical_deduction_five_objects",
                            "logical_deduction_seven_objects", "logical_deduction_three_objects",
                            "movie_recommendation", "multistep_arithmetic_two", "navigate",
                            "object_counting", "penguins_in_a_table", "reasoning_about_colored_objects",
                            "ruin_names", "salient_translation_error_detection", "snarks",
                            "sports_understanding", "temporal_sequences",
                            "tracking_shuffled_objects_five_objects",
                            "tracking_shuffled_objects_seven_objects",
                            "tracking_shuffled_objects_three_objects",
                            "web_of_lies", "word_sorting",
                        ])
    parser.add_argument("--batch_size", type=int, default=4)
    parser.add_argument("--cut_off", type=int, default=768)
    parser.add_argument("--top_k", type=int, default=250)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--learning_rate", type=str, default="5e-05",
                        help="Learning rate used when training the adapter (for path resolution)")
    parser.add_argument("--max_epoch", type=int, default=2,
                        help="Epochs used when training the adapter (for path resolution)")
    return parser

args = build_parser().parse_args()

# ---------------------------------------------------------------------------
# Model detection utilities
# ---------------------------------------------------------------------------
def detect_model_family(model_name):
    lower = model_name.lower()
    if "mistral" in lower:
        return "mistral"
    elif "llama" in lower:
        return "llama3"
    else:
        raise ValueError(f"Unsupported model family for: {model_name}. Add a chat template for this model.")

# ---------------------------------------------------------------------------
# Path setup
# ---------------------------------------------------------------------------
expert_model_short = args.expert_model_name.split("/")[-1]
target_model_short = args.target_model_name.split("/")[-1]

if input_synthetic_data_path is None:
    raise ValueError(
        "Please set 'input_synthetic_data_path' at the top of this script.\n"
        "It should point to the directory containing {task_name}_diverse_500_data.json files."
    )
data_path = os.path.join(input_synthetic_data_path, f"{args.task_name}_diverse_500_data.json")

# Adapter paths — compatible with BBH_SFT.py checkpointing convention
base_adapter_path = (
    f"./checkpoints/expert/{args.task_name}"
    f"/{args.learning_rate}-{args.max_epoch}-{expert_model_short}"
)

def get_adapter_path():
    if os.path.exists(base_adapter_path):
        print(f"Using adapter: {base_adapter_path}")
        return base_adapter_path
    print(f"WARNING: No adapter found at: {base_adapter_path}")
    return base_adapter_path

adapter_path = get_adapter_path()

output_dir = (
    f"./results/excess_losses"
    f"/query_{args.queries_from}_EXPERT_{expert_model_short}_on_target_{target_model_short}"
    f"/{args.task_name}/"
)

# ---------------------------------------------------------------------------
# System prompt — loaded from prompts.json
# ---------------------------------------------------------------------------
def load_prompts(path="./prompts.json"):
    with open(path, "r") as f:
        return json.load(f)

def get_system_prompt(task_name, prompts):
    prompt = prompts.get(task_name, prompts["default"])
    print(f"System prompt for '{task_name}': '{prompt}'")
    return prompt

PROMPTS = load_prompts("./prompts.json")
SYSTEM_PROMPT = get_system_prompt(args.task_name, PROMPTS)

# ---------------------------------------------------------------------------
# Chat templates
# ---------------------------------------------------------------------------
CHAT_TEMPLATES = {
    "mistral": """
{% if messages[0]['role'] == 'system' %}
{% set loop_messages = messages[1:] %}
{% set system_message = messages[0]['content'].strip() + '\\n' %}
{% else %}
{% set loop_messages = messages %}
{% set system_message = '' %}
{% endif %}
{% for message in loop_messages %}
    {% if loop.index0 == 0 %}
        {% set content = system_message + message['content'] %}
    {% else %}
        {% set content = message['content'] %}
    {% endif %}
    {% if message['role'] == 'user' %}
        {{ '[INST] ' + content.strip() + ' [/INST]' }}
    {% elif message['role'] == 'assistant' %}
        {{ ' ' + content.strip() + ' ' + eos_token }}
    {% endif %}
{% endfor %}
""",
    "llama3": """
{% set bos_token = '<|begin_of_text|>' %}
{% set start_header = '<|start_header_id|>' %}
{% set end_header = '<|end_header_id|>' %}
{% set eot = '<|eot_id|>' %}
{{ bos_token }}
{% if messages[0]['role'] == 'system' %}
    {{ start_header }}system{{ end_header }}
    {{ messages[0]['content'].strip() }}{{ eot }}
    {% set loop_messages = messages[1:] %}
{% else %}
    {% set loop_messages = messages %}
{% endif %}
{% for message in loop_messages %}
    {{ start_header }}{{ message['role'] }}{{ end_header }}
    {{ message['content'].strip() }}{{ eot }}
{% endfor %}
{{ start_header }}assistant{{ end_header }}
""",
}

def apply_chat_template(example, tokenizer, model_name):
    family = detect_model_family(model_name)
    tokenizer.chat_template = CHAT_TEMPLATES[family]
    print(f"Using {family} chat template")
    example["text_prompt"] = tokenizer.apply_chat_template(
        example["prompt"], tokenize=False, add_generation_prompt=True
    )
    example["text_chosen"] = tokenizer.apply_chat_template(
        example["chosen"], tokenize=False
    )
    return example

# ---------------------------------------------------------------------------
# Model loading
# ---------------------------------------------------------------------------
def load_model_and_tokenizer(model_name, access_token=None):
    """Load base model + tokenizer (adapter is attached separately in main)."""
    tokenizer = AutoTokenizer.from_pretrained(
        adapter_path if os.path.exists(adapter_path) else model_name,
        token=access_token,
    )
    tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        token=access_token,
    )
    model.config.pad_token_id = tokenizer.eos_token_id
    model.config.use_cache = False
    model.gradient_checkpointing_enable()
    model = prepare_model_for_kbit_training(model)
    return model, tokenizer

# ---------------------------------------------------------------------------
# Dataset preparation
# ---------------------------------------------------------------------------
def build_dataset(data_path, tokenizer, model_name, cut_off):
    print(f"Loading data from: {data_path}")
    with open(data_path, "r") as f:
        raw_json = json.load(f)
    examples = raw_json.get("examples", [])
    print(f"Loaded {len(examples)} examples")
    if not examples:
        raise ValueError(f"No examples found in {data_path}")

    processed = []
    for ex in examples:
        fmt = apply_chat_template(
            {
                "prompt": [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": ex["input"]},
                ],
                "chosen": [{"role": "assistant", "content": ex["target"]}],
            },
            tokenizer,
            model_name,
        )
        processed.append({"prompt": fmt["text_prompt"], "chosen": fmt["text_chosen"]})

    if processed:
        print(f"Sample prompt:\n{processed[0]['prompt'][:300]}...")
        print(f"Sample chosen:\n{processed[0]['chosen'][:100]}...")

    def tokenize_example(example):
        tok_prompt = tokenizer(
            example["prompt"], truncation=True, max_length=cut_off,
            add_special_tokens=False, return_tensors=None,
        )
        tok_chosen = tokenizer(
            example["chosen"], truncation=True, max_length=cut_off,
            add_special_tokens=False, return_tensors=None,
        )
        return {
            "input_ids": tok_prompt["input_ids"] + tok_chosen["input_ids"],
            "attention_mask": tok_prompt["attention_mask"] + tok_chosen["attention_mask"],
            "labels": [-100] * len(tok_prompt["input_ids"]) + tok_chosen["input_ids"],
        }

    tokenized = [tokenize_example(ex) for ex in processed]
    return Dataset.from_list(tokenized), examples

# ---------------------------------------------------------------------------
# Loss computation
# ---------------------------------------------------------------------------
def compute_excess_loss(expert_model, amateur_model, input_ids, attention_mask, labels):
    """Compute token-level excess loss (amateur - expert) on output tokens only."""
    with torch.no_grad():
        loss_fn = nn.CrossEntropyLoss(reduction="none")

        expert_logits = expert_model(
            input_ids=input_ids, attention_mask=attention_mask, labels=labels
        ).logits[:, :-1, :].contiguous()
        targets = labels[:, 1:].contiguous()
        expert_loss = loss_fn(
            expert_logits.view(-1, expert_logits.size(-1)), targets.view(-1)
        ).view(targets.shape)

        amateur_logits = amateur_model(
            input_ids=input_ids, attention_mask=attention_mask, labels=labels
        ).logits[:, :-1, :].contiguous()
        amateur_loss = loss_fn(
            amateur_logits.view(-1, amateur_logits.size(-1)), targets.view(-1)
        ).view(targets.shape)

        output_mask = (targets != -100).float()
        expert_loss = expert_loss * output_mask
        amateur_loss = amateur_loss * output_mask
        excess_loss = amateur_loss - expert_loss

    return excess_loss, expert_loss, amateur_loss

# ---------------------------------------------------------------------------
# Align-specific: output-only extraction
# ---------------------------------------------------------------------------
def extract_output_only_data(excess_batches, original_examples, tokenizer, top_k_stats):
    """Extract output tokens, their excess losses, and decoded text for each top-k sample."""
    print("\n[4.5/5] Extracting output-only excess loss data...")
    output_only_data = []

    for stat in top_k_stats:
        batch_data = excess_batches[stat["batch_idx"]]
        i = stat["batch_sample_idx"]

        input_ids = batch_data["input_ids"][i]
        labels = batch_data["labels"][i]
        excess_losses = batch_data["excess_losses"][i]

        labels_shifted = labels[1:]
        output_mask = (labels_shifted != -100)
        if output_mask.sum() == 0:
            continue

        output_positions = torch.where(output_mask)[0]
        output_token_ids = input_ids[output_positions + 1].tolist()
        output_excess_losses = excess_losses[output_mask].tolist()
        output_text = tokenizer.decode(output_token_ids, skip_special_tokens=True)
        full_sequence_text = tokenizer.decode(input_ids, skip_special_tokens=True)

        original_example = original_examples[stat["sample_idx"]]

        output_only_data.append({
            "sample_idx": stat["sample_idx"],
            "input_text": original_example["input"],
            "output_text": output_text,
            "expected_output": original_example["target"],
            "output_token_ids": output_token_ids,
            "output_excess_losses": output_excess_losses,
            "full_sequence_text": full_sequence_text,
            "mean_excess_loss": stat["mean_excess_loss"],
            "num_output_tokens": len(output_token_ids),
            "source_model_info": {
                "model_name": args.expert_model_name,
                "model_family": detect_model_family(args.expert_model_name),
                "system_prompt": SYSTEM_PROMPT,
                "task_name": args.task_name,
            },
        })

    print(f"Extracted output-only data for {len(output_only_data)} samples")
    if output_only_data:
        s = output_only_data[0]
        print(f"  Input: {s['input_text'][:100]}...")
        print(f"  Output: {s['output_text']}")
        print(f"  Output tokens: {len(s['output_token_ids'])}")
        print(f"  Excess losses (first 5): {s['output_excess_losses'][:5]}")
        print(f"  Mean excess: {s['mean_excess_loss']:.4f}")
    return output_only_data

# ---------------------------------------------------------------------------
# Align-specific: batch-level binary masks for k values
# ---------------------------------------------------------------------------
def create_binary_masks_for_k_values(
    output_only_data,
    k_values=(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0),
    *,
    excess_batches,
    batch_size,
):
    """
    Batch-level top-k% selection over valid output tokens per batch.

    For each batch:
      1) Identify valid output positions: (labels[:,1:] != -100) & attention[:,1:]
      2) Flatten across all sequences, select top k% by excess loss.
      3) Map selections back per sequence, compressed to output-only order.
      4) Emit per-sample binary masks only for samples in output_only_data (top-K).
    """
    print(f"\n[4.7/5] Creating binary masks (batch-level) for k values: {list(k_values)}")

    by_sample = {s["sample_idx"]: s for s in output_only_data}

    def est_sample_idx(batch_idx, i):
        return batch_idx * batch_size + i

    k_binary_data = {k: [] for k in k_values}

    for batch in excess_batches:
        B = batch["excess_losses"].shape[0]
        S1 = batch["excess_losses"].shape[1]

        labels_shifted = batch["labels"][:, 1:]
        attn_shifted = batch["attention_mask"][:, 1:]
        out_mask = (labels_shifted != -100) & attn_shifted.bool()

        flat_excess = batch["excess_losses"].view(-1)
        flat_mask = out_mask.view(-1)
        valid_idx = torch.nonzero(flat_mask, as_tuple=False).squeeze(-1)
        if valid_idx.numel() == 0:
            continue

        valid_excess = flat_excess[valid_idx]

        output_only_pos_per_i = []
        output_token_ids_per_i = []
        for i in range(B):
            out_pos_i = out_mask[i]
            output_only_pos_per_i.append(out_pos_i)
            output_token_ids_per_i.append(
                batch["input_ids"][i, 1:][out_pos_i].tolist() if out_pos_i.any() else []
            )

        for k in k_values:
            num_select = max(1, int(valid_excess.numel() * k))
            _, top_local = torch.topk(valid_excess, num_select, largest=True)
            chosen_flat_idx = valid_idx[top_local]

            chosen_flat_mask = torch.zeros_like(flat_mask, dtype=torch.bool)
            chosen_flat_mask[chosen_flat_idx] = True
            chosen_mask = chosen_flat_mask.view(B, S1)

            for i in range(B):
                sidx = est_sample_idx(int(batch["batch_idx"]), i)
                if sidx not in by_sample:
                    continue

                out_pos_i = output_only_pos_per_i[i]
                if out_pos_i.any():
                    chosen_i = chosen_mask[i] & out_pos_i
                    bin_mask = chosen_i[out_pos_i].float().tolist()
                else:
                    bin_mask = []

                src = by_sample[sidx]
                output_token_ids = output_token_ids_per_i[i]
                num_selected = float(sum(bin_mask))
                num_output_tokens = len(output_token_ids)

                k_binary_data[k].append({
                    "sample_idx": sidx,
                    "input_text": src["input_text"],
                    "output_text": src["output_text"],
                    "expected_output": src["expected_output"],
                    "output_token_ids": output_token_ids,
                    "output_excess_losses": src["output_excess_losses"],
                    "binary_mask": bin_mask,
                    "k_percent": k,
                    "num_selected": num_selected,
                    "selection_ratio": (num_selected / num_output_tokens) if num_output_tokens > 0 else 0.0,
                    "mean_excess_loss": src["mean_excess_loss"],
                    "num_output_tokens": num_output_tokens,
                    "source_model_info": src["source_model_info"],
                })

    for k, items in k_binary_data.items():
        total_tokens = sum(len(it["output_token_ids"]) for it in items)
        total_selected = sum(it["num_selected"] for it in items)
        ratio = (total_selected / total_tokens) if total_tokens > 0 else 0.0
        print(f"  k={k}: {int(total_selected)}/{total_tokens} tokens selected (avg ratio: {ratio:.3f})")

    return k_binary_data

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main():
    set_seed(args.seed)

    print("=" * 60)
    print("BBH EXCESS LOSS COMPUTATION")
    print("=" * 60)
    print(f"Expert model:    {args.expert_model_name}")
    print(f"Target model:    {args.target_model_name}")
    print(f"Task:            {args.task_name}")
    print(f"  Family:        {detect_model_family(args.expert_model_name)}")
    print(f"System prompt:   '{SYSTEM_PROMPT}'")
    print(f"Data path:       {data_path}")
    print(f"Adapter path:    {adapter_path}")
    print(f"Output dir:      {output_dir}")
    print("=" * 60)

    # [1/5] Load models
    print("\n[1/5] Loading models and tokenizer...")
    base_model, tokenizer = load_model_and_tokenizer(args.expert_model_name, args.access_token)

    expert_model = PeftModel.from_pretrained(base_model, adapter_path, is_trainable=False)
    expert_model.eval()

    amateur_model = AutoModelForCausalLM.from_pretrained(
        args.expert_model_name,
        device_map="auto",
        torch_dtype=torch.bfloat16,
        token=args.access_token,
    )
    amateur_model.config.pad_token_id = tokenizer.eos_token_id
    amateur_model.config.use_cache = False
    amateur_model.gradient_checkpointing_enable()
    amateur_model = prepare_model_for_kbit_training(amateur_model)
    amateur_model.eval()

    # [2/5] Build dataset
    print("\n[2/5] Preparing dataset...")
    dataset, original_examples = build_dataset(
        data_path, tokenizer, args.expert_model_name, args.cut_off
    )
    dataloader = DataLoader(
        dataset,
        batch_size=args.batch_size,
        shuffle=False,
        collate_fn=DataCollatorForSeq2Seq(
            tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True
        ),
    )
    print(f"Total samples: {len(dataset)}")

    # [3/5] Compute excess losses
    print("\n[3/5] Computing excess losses...")
    excess_batches = []
    for batch_idx, batch in enumerate(tqdm(dataloader, desc="Processing batches")):
        batch = {k: v.cuda() for k, v in batch.items()}
        excess_loss, expert_loss, amateur_loss = compute_excess_loss(
            expert_model, amateur_model,
            batch["input_ids"], batch["attention_mask"], batch["labels"],
        )
        excess_batches.append({
            "batch_idx": batch_idx,
            "input_ids": batch["input_ids"].cpu(),
            "attention_mask": batch["attention_mask"].cpu(),
            "labels": batch["labels"].cpu(),
            "excess_losses": excess_loss.cpu(),
            "expert_losses": expert_loss.cpu(),
            "amateur_losses": amateur_loss.cpu(),
        })

    # [4/5] Per-sample statistics
    print("\n[4/5] Computing sample statistics...")
    sample_stats = []
    sample_idx = 0
    for batch_data in excess_batches:
        for i in range(batch_data["excess_losses"].shape[0]):
            labels_shifted = batch_data["labels"][i, 1:]
            output_mask = (labels_shifted != -100).float()
            mean_excess = (
                (batch_data["excess_losses"][i] * output_mask).sum() / output_mask.sum()
                if output_mask.sum() > 0 else 0.0
            )
            sample_stats.append({
                "sample_idx": sample_idx,
                "batch_idx": batch_data["batch_idx"],
                "batch_sample_idx": i,
                "mean_excess_loss": mean_excess.item() if hasattr(mean_excess, "item") else float(mean_excess),
                "num_output_tokens": output_mask.sum().item(),
            })
            sample_idx += 1

    sample_stats.sort(key=lambda x: x["mean_excess_loss"], reverse=True)
    top_k_stats = sample_stats[: args.top_k]

    # Prepare top-k tensors and examples
    top_k_tensors = []
    top_k_examples = []
    for stat in top_k_stats:
        bd = excess_batches[stat["batch_idx"]]
        i = stat["batch_sample_idx"]
        top_k_tensors.append({
            "input_ids": bd["input_ids"][i],
            "attention_mask": bd["attention_mask"][i],
            "labels": bd["labels"][i],
            "excess_losses": bd["excess_losses"][i],
            "expert_losses": bd["expert_losses"][i],
            "amateur_losses": bd["amateur_losses"][i],
            "mean_excess_loss": stat["mean_excess_loss"],
            "num_output_tokens": stat["num_output_tokens"],
        })
        top_k_examples.append(original_examples[stat["sample_idx"]])

    # [4.5/5] Output-only extraction (align)
    output_only_data = extract_output_only_data(
        excess_batches, original_examples, tokenizer, top_k_stats
    )

    # [4.7/5] Binary masks for k values (align)
    k_values = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
    k_binary_data = create_binary_masks_for_k_values(
        output_only_data,
        k_values,
        excess_batches=excess_batches,
        batch_size=args.batch_size,
    )

    # [5/5] Save all outputs
    print(f"\n[5/5] Saving results to {output_dir}...")
    os.makedirs(output_dir, exist_ok=True)

    config = {
        "expert_model_name": args.expert_model_name,
        "target_model_name": args.target_model_name,
        "task_name": args.task_name,
        "system_prompt": SYSTEM_PROMPT,
        "expert_model_family": detect_model_family(args.expert_model_name),
        "data_path": data_path,
        "adapter_path": adapter_path,
        "top_k": args.top_k,
    }

    # --- No-align outputs ---
    torch.save(
        {"excess_loss_data": excess_batches, "sample_stats": sample_stats, "config": config},
        os.path.join(output_dir, "all_excess_losses.pt"),
    )
    torch.save(
        {"top_k_tensors": top_k_tensors, "top_k_sample_info": top_k_stats},
        os.path.join(output_dir, f"top_{args.top_k}_tensors.pt"),
    )
    with open(os.path.join(output_dir, f"top_{args.top_k}_data.json"), "w") as f:
        json.dump({"examples": top_k_examples, "config": config}, f, indent=2)

    # --- Align outputs ---
    torch.save(
        {
            "output_only_data": output_only_data,
            "config": config,
            "extraction_info": {
                "total_samples": len(output_only_data),
                "source_tokenizer": args.expert_model_name,
                "extraction_method": "output_tokens_only",
                "ready_for_alignment": True,
            },
        },
        os.path.join(output_dir, f"top_{args.top_k}_output_only_excess_losses.pt"),
    )
    with open(os.path.join(output_dir, f"top_{args.top_k}_output_only_data.json"), "w") as f:
        json.dump(
            {
                "output_only_data": output_only_data,
                "config": config,
                "usage": "Output tokens and their excess losses for cross-tokenizer alignment",
            },
            f,
            indent=2,
        )

    print(f"\nSaving binary mask files for k values...")
    for k_percent, k_data in k_binary_data.items():
        k_file = os.path.join(output_dir, f"top_{args.top_k}_output_only_k{k_percent}_binary.pt")
        torch.save(
            {
                "k_binary_data": k_data,
                "k_percent": k_percent,
                "config": config,
                "binary_info": {
                    "total_samples": len(k_data),
                    "k_percent": k_percent,
                    "source_tokenizer": args.expert_model_name,
                    "selection_method": f"batch_top_{int(k_percent * 100)}%_excess_loss_over_valid_outputs",
                    "ready_for_training": True,
                },
            },
            k_file,
        )
        total_tokens = sum(item["num_output_tokens"] for item in k_data)
        total_selected = sum(item["num_selected"] for item in k_data)
        avg_ratio = (total_selected / total_tokens) if total_tokens > 0 else 0.0
        print(f"  • k={k_percent}: {int(total_selected)}/{total_tokens} tokens (ratio: {avg_ratio:.3f})")
        print(f"    → top_{args.top_k}_output_only_k{k_percent}_binary.pt")

    # Summary
    avg_output_tokens = sum(s["num_output_tokens"] for s in top_k_stats) / max(1, len(top_k_stats))
    avg_excess_loss = sum(s["mean_excess_loss"] for s in top_k_stats) / max(1, len(top_k_stats))

    print("\n" + "=" * 60)
    print("RESULTS SUMMARY")
    print("=" * 60)
    print(f"• Processed {len(dataset)} samples")
    print(f"• Selected top {args.top_k} samples by excess loss")
    print(f"• Avg output tokens/sample: {avg_output_tokens:.1f}")
    print(f"• Avg excess loss:          {avg_excess_loss:.4f}")
    print(f"• Output dir:               {output_dir}")
    print(f"• System prompt:            '{SYSTEM_PROMPT}'")
    print(f"• Model family:             {detect_model_family(args.expert_model_name)}")
    print(f"• [No-align]  all_excess_losses.pt")
    print(f"• [No-align]  top_{args.top_k}_tensors.pt")
    print(f"• [No-align]  top_{args.top_k}_data.json")
    print(f"• [Align]     top_{args.top_k}_output_only_excess_losses.pt")
    print(f"• [Align]     top_{args.top_k}_output_only_data.json")
    for k in k_values:
        print(f"• [Align]     top_{args.top_k}_output_only_k{k}_binary.pt")
    print("=" * 60)


if __name__ == "__main__":
    main()